apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
    cacheTTL: 2m
  x509:
    clientCAFile: /etc/kubernetes/tls/ca.pem
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m
    cacheUnauthorizedTTL: 30s
cgroupDriver: systemd
clusterDNS:
- __DNS__SERVER__
clusterDomain: cluster.local
address: 0.0.0.0
port: 10250
readOnlyPort: 0
failSwapOn: true
evictionHard:
  memory.available: 100Mi
  nodefs.available: 10%
  nodefs.inodesFree: 5%
  imagefs.available: 15%
hairpinMode: promiscuous-bridge
maxOpenFiles: 1000000
maxPods: 110
rotateCertificates: true
